server:
    port: 8080
    session:
      timeout: 30
    tomcat:
      accesslog:
        enabled: true
    context-path: /client/

logging:
    level:
        root: debug
        com.xxx.template: debug
spring:
    mvc:
        view:
            prefix: /WEB-INF/jsp/
            suffix: .jsp