server:
    port: 8080
    session:
      timeout: 30
    context-path: /server/

logging:
    level:
        root: debug
        com.xxx.template: debug
        java.sql: debug

spring:
    datasource:
        name: demo
        url: jdbc:mysql://localhost:3306/demo
        username: root
        password: 123456
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 1
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    freemarker:
        cache: false
        request-context-attribute: request
    messages:
      encoding: UTF-8

#以下属性不可用
mybatis:
    ##pagehelper:
    ##    dialect: mysql
    ##    reasonable: true
    ##    supportMethodsArguments: true
    ##    returnPageInfo: check
    ##    params: count=countSql
    ##mapper:
    ##    mappers: tk.mybatis.springboot.util.MyMapper
    ##    notEmpty: true
    ##    style: camelhump
    ##mapperScanner:
    ##    basePackage: tk.mybatis.springboot.mapper
    mapper-locations: classpath:mapper/**/*.xml
    type-aliases-package: com.xxx.template.*.model